# Form implementation generated from reading ui file 'ui/auth.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(400, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(AuthWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(parent=AuthWindow)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line_login = QtWidgets.QLineEdit(parent=AuthWindow)
        self.line_login.setObjectName("line_login")
        self.verticalLayout.addWidget(self.line_login)
        self.line_password = QtWidgets.QLineEdit(parent=AuthWindow)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_password.setObjectName("line_password")
        self.verticalLayout.addWidget(self.line_password)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_login = QtWidgets.QPushButton(parent=AuthWindow)
        self.button_login.setObjectName("button_login")
        self.horizontalLayout.addWidget(self.button_login)
        self.button_guest = QtWidgets.QPushButton(parent=AuthWindow)
        self.button_guest.setObjectName("button_guest")
        self.horizontalLayout.addWidget(self.button_guest)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "Аквилон - Авторизация"))
        self.label_title.setText(_translate("AuthWindow", "Аквилон"))
        self.label_title.setStyleSheet(_translate("AuthWindow", "font-size: 28px; font-weight: bold; color: #d35400;"))
        self.line_login.setPlaceholderText(_translate("AuthWindow", "Логин"))
        self.line_login.setStyleSheet(_translate("AuthWindow", "padding: 10px; font-size: 14px;"))
        self.line_password.setPlaceholderText(_translate("AuthWindow", "Пароль"))
        self.line_password.setStyleSheet(_translate("AuthWindow", "padding: 10px; font-size: 14px;"))
        self.button_login.setText(_translate("AuthWindow", "Войти"))
        self.button_login.setStyleSheet(_translate("AuthWindow", "background: #27ae60; color: white; padding: 10px; font-weight: bold; border-radius: 5px;"))
        self.button_guest.setText(_translate("AuthWindow", "Гость"))
        self.button_guest.setStyleSheet(_translate("AuthWindow", "background: #3498db; color: white; padding: 10px; border-radius: 5px;"))
