# Form implementation generated from reading ui file 'ui/menu.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(1000, 700)
        MenuWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setObjectName("main_layout")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setObjectName("top_layout")
        self.label_logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_logo.setObjectName("label_logo")
        self.top_layout.addWidget(self.label_logo)
        self.line_search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_search.setObjectName("line_search")
        self.top_layout.addWidget(self.line_search)
        self.combo_category = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_category.setMinimumWidth(120)
        self.combo_category.setObjectName("combo_category")
        self.top_layout.addWidget(self.combo_category)
        self.combo_supplier = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_supplier.setMinimumWidth(150)
        self.combo_supplier.setObjectName("combo_supplier")
        self.top_layout.addWidget(self.combo_supplier)
        self.button_sort = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_sort.setObjectName("button_sort")
        self.top_layout.addWidget(self.button_sort)
        self.button_orders = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_orders.setObjectName("button_orders")
        self.top_layout.addWidget(self.button_orders)
        self.button_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_add.setObjectName("button_add")
        self.top_layout.addWidget(self.button_add)
        self.label_user = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_user.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_user.setObjectName("label_user")
        self.top_layout.addWidget(self.label_user)
        self.button_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_exit.setObjectName("button_exit")
        self.top_layout.addWidget(self.button_exit)
        self.main_layout.addLayout(self.top_layout)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollWidget = QtWidgets.QWidget()
        self.scrollWidget.setObjectName("scrollWidget")
        self.menu_layout = QtWidgets.QVBoxLayout(self.scrollWidget)
        self.menu_layout.setObjectName("menu_layout")
        self.scrollArea.setWidget(self.scrollWidget)
        self.main_layout.addWidget(self.scrollArea)
        self.label_status = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.main_layout.addWidget(self.label_status)
        MenuWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "Аквилон"))
        self.label_logo.setText(_translate("MenuWindow", "Аквилон"))
        self.label_logo.setStyleSheet(_translate("MenuWindow", "font-size: 20px; font-weight: bold; color: #d35400;"))
        self.line_search.setPlaceholderText(_translate("MenuWindow", "Поиск..."))
        self.line_search.setStyleSheet(_translate("MenuWindow", "padding: 8px;"))
        self.button_sort.setText(_translate("MenuWindow", "Сортировка ↑"))
        self.button_orders.setText(_translate("MenuWindow", "Заказы"))
        self.button_add.setText(_translate("MenuWindow", "Добавить"))
        self.label_user.setText(_translate("MenuWindow", "Гость"))
        self.label_user.setStyleSheet(_translate("MenuWindow", "font-size: 14px; font-weight: bold;"))
        self.button_exit.setText(_translate("MenuWindow", "Выход"))
        self.button_exit.setStyleSheet(_translate("MenuWindow", "background: #e74c3c; color: white;"))
        self.label_status.setStyleSheet(_translate("MenuWindow", "color: gray; padding: 5px;"))
